#!/bin/bash

kswitch -p $1                                                                                                   
if [[ $? != 0 ]]; then                                                                                          
    echo "expired or not exist, asking for new one"
    kinit -l 9999999999 $1                                                                                      
    kswitch -p $1                                                                                                   
fi  
# klist -s
